backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
  - name: content
    identifier_field: "{{page}}_{{position}}"
    slug: "{{page}}_{{position}}_{{title}}"
    label: Content Sections
    folder: content
    create: true
    summary: "Section #{{position}} on {{page}}\n Heading: {{title}}"
    fields:
      - name: page
        label: Page
        widget: select
        options: ["Home", "Volunteer", "Get help", "Health & Safety", "More support", "Contact us", "About us"]
      - { name: title, label: Title, widget: string, required: false }
      - { name: position, label: Position, widget: number, default: 0, valueType: "int" }
      - { name: body, label: Body, widget: markdown }
      - { name: style, label: Style, widget: select, options: ["info", "warning"], required: false}
  - name: resources
    identifier_field: "{{page}}_{{position}}"
    slug: "{{page}}_{{section}}_{{position}}_{{title}}"
    label: Resources
    folder: resources
    create: true
    summary: "{{page}} {{section}} {{title}}"
    fields:
      - { name: page, label: Page, widget: select, options: ["Home", "Volunteer", "Get help", "Health & Safety", "More support", "Contact us", "About us"] }
      - { name: position, label: Position, widget: number, default: 0, valueType: "int" }
      - { name: title, label: Title, widget: string }
      - { name: section, label: Section, widget: string }
      - { name: body, label: Text, widget: string }
      - { name: website, label: Website, widget: string, required: false }
      - { name: phone, label: Phone, widget: string, required: false }
