backend:
  name: git-gateway
  branch: master

media_folder: static/assets
public_folder: /assets
collections:
  - name: content
    label: Content Sections
    folder: content
    create: true
    fields:
      - { name: page, label: Page, widget: select, options: ["Home", "Volunteer", "Get help", "Health & Safety", "More support", "Contact us", "About us"] }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
